import turtle

r=50
turtle.circle(5)
turtle.up()
turtle.fd(20)
turtle.down()
turtle.setheading(0)
ang=turtle.towards(20,200)
dist=turtle.distance(20,200)
turtle.left(ang)
turtle.fd(dist)
x=turtle.xcor()
y=turtle.ycor()
print('{} , {}, {}'.format(x,y,ang))
turtle.circle(5)
turtle.setheading(0)
ang=turtle.towards(200,20)
dist=turtle.distance(200,20)
turtle.right(-ang)
turtle.fd(dist)
x=turtle.xcor()
y=turtle.ycor()
turtle.backward(20)
turtle.left(90)
turtle.fd(20)
dist=turtle.distance(x,y)
turtle.goto(x,y)
turtle.left(135)
turtle.fd(dist)
turtle.right(135)
turtle.fd(20)
turtle.circle(5)
print('{} , {}, {}'.format(x,y,ang))
turtle.mainloop()
